### ISSUE TITLE
IF tag highlighting

### ISSUE THREAD

**Issue by jakesergeant** [matt-downs/vscode-neto-base#2]
IF/ELSEIF has some highlighting issues. The older ENDIF tag isn't highlighting like the ELSE.

![screen shot 2017-11-09 at 9 29 21 am](https://user-images.githubusercontent.com/5865846/32580357-99e6001e-c530-11e7-8eaa-ff26e053d583.jpg)

**Comment by matt-downs** [comment]
The following line will have to be changed to look for `/` or `end`:
https://github.com/matt-downs/vscode-neto-base/blob/master/syntaxes/base.tmLanguage.json#L18
